flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: barnard59
    - name: barnard59-base
    - name: barnard59-core
    - name: barnard59-csvw
    - name: barnard59-formats
    - name: barnard59-ftp
    - name: barnard59-graph-store
    - name: barnard59-http
    - name: barnard59-rdf
    - name: barnard59-sparql
    - name: barnard59-validate-shacl
    - name: barnard59-validation
ignore:
  - test
  - "packages/*/test/**/*"
