name: Fig integration

on:
  push:
    tags:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.sha }}

jobs:
  push-autocomplete-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - run: npm run generate-autocomplete-spec
        working-directory: packages/cli

      - name: Create Autocomplete PR
        uses: withfig/push-to-fig-autocomplete-action@v2
        with:
          token: ${{ secrets.FIG_PAT }}
          autocomplete-spec-name: barnard59
          spec-path: packages/cli/fig-spec.ts
          integration: commander
